# Generated by Django 6.0.3 on 2026-08-17 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_adjustment_index', models.CharField(default='IGPM', max_length=10)),
                ('contract_alert_days', models.IntegerField(default=60)),
                ('notify_expiring_contracts', models.BooleanField(default=True)),
                ('notify_overdue_charges', models.BooleanField(default=True)),
                ('notify_vacant_properties', models.BooleanField(default=True)),
                ('notify_upcoming_expenses', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_rent', to='finance.bankaccount')),
                ('default_rent_chart_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_rent', to='finance.chartaccount')),
            ],
            options={
                'verbose_name': 'Configurações do sistema',
            },
        ),
    ]
