# Generated by Django 6.0.3 on 2026-08-17 01:20

import core_app.validators.validate_numbers
import core_app.validators.validate_values
import tenants.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[core_app.validators.validate_values.validate_not_blank])),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[core_app.validators.validate_values.validate_not_blank, tenants.validators.validate_cpf])),
                ('email', models.EmailField(max_length=254, unique=True, validators=[core_app.validators.validate_values.validate_not_blank])),
                ('phone_number', models.CharField(max_length=20, validators=[core_app.validators.validate_values.validate_not_blank])),
                ('guarantor', models.BooleanField(default=False)),
                ('profession', models.CharField(max_length=100, validators=[core_app.validators.validate_values.validate_not_blank])),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=10, validators=[core_app.validators.validate_numbers.validate_positive, core_app.validators.validate_values.validate_not_blank])),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
