# Generated by Django 6.0.3 on 2026-08-26 16:55

import core_app.validators.validate_values
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, validators=[core_app.validators.validate_values.validate_not_blank]),
        ),
    ]
