# Generated by Django 6.0.3 on 2026-08-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Disponivel'), (1, 'Alugado'), (2, 'Em Manutencao'), (3, 'Vendido')], default=0),
        ),
    ]
